script: bundle exec rake -f spec/spec.rake spec
language: ruby
cache: bundler
bundler_args: --without development
rvm:
  - 2.6.5
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - RACK_ENV=test bundle exec rake db:migrate
  - RACK_ENV=test bundle exec rake db:seed:test
before_install: gem install bundler
