# TO PUT INTO MYSQL:
# CREATE USER 'eventreg'@'localhost' IDENTIFIED BY 'letmein';
# GRANT ALL ON eventreg_development.* TO 'eventreg'@'localhost';
# GRANT ALL ON eventreg_production.* TO 'eventreg'@'localhost';
# GRANT ALL ON eventreg_test.* TO 'eventreg'@'localhost';

development:
  adapter: mysql2
  encoding: utf8
  database: eventreg_development
  username: eventreg
  password: letmein
  host: localhost
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  database: eventreg_test
  username: eventreg
  password: letmein
  host: localhost
  port: 3306

production:
  adapter: mysql2
  encoding: utf8
  database: eventreg_production
  username: eventreg
  password: letmein
  host: localhost
  port: 3306