# TO PUT INTO MYSQL:
# CREATE USER 'eventreg'@'localhost' IDENTIFIED BY 'letmein';
# GRANT ALL ON eventreg_development.* TO 'eventreg'@'localhost';
# GRANT ALL ON eventreg_production.* TO 'eventreg'@'localhost';
# GRANT ALL ON eventreg_test.* TO 'eventreg'@'localhost';

test:
  adapter: postgresql
  encoding: utf8
  database: travis_ci_test

development:
  adapter: postgresql
  encoding: utf8
  url: <%= ENV['DATABASE_URL'] %>

staging:
  adapter: postgresql
  encoding: utf8
  url: <%= ENV['DATABASE_URL'] %>

production:
  adapter: postgresql
  encoding: utf8
  url: <%= ENV['DATABASE_URL'] %>
