development:
  adapter: mysql2
  encoding: utf8
  database: diversity_development
  username: diversity
  password: kurdmcfrogspleen
  host: localhost
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  database: diversity_test
  username: diversity
  password: kurdmcfrogspleen
  host: localhost
  port: 3306

production:
  adapter: mysql2
  encoding: utf8
  database: diversity_production
  username: diversity
  password: kurdmcfrogspleen
  host: localhost
  port: 3306