# TO PUT INTO MYSQL:
# CREATE USER 'eventreg'@'localhost' IDENTIFIED BY 'letmein';
# GRANT ALL ON eventreg_development.* TO 'eventreg'@'localhost';
# GRANT ALL ON eventreg_production.* TO 'eventreg'@'localhost';
# GRANT ALL ON eventreg_test.* TO 'eventreg'@'localhost';

development:
  adapter: postgresql 
  encoding: utf8
  database: eventreg_development
  username: eventreg
  password: letmein
  host: localhost

test:
  adapter: postgresql 
  encoding: utf8
  database: eventreg_test
  username: eventreg
  password: letmein
  host: localhost

production:
  url: <%= ENV['DATABASE_URL'] %>
