# TO PUT INTO MYSQL:
# CREATE USER 'eventreg'@'localhost' IDENTIFIED BY 'letmein';
# GRANT ALL ON eventreg_development.* TO 'eventreg'@'localhost';
# GRANT ALL ON eventreg_production.* TO 'eventreg'@'localhost';
# GRANT ALL ON eventreg_test.* TO 'eventreg'@'localhost';

development:
  adapter: sqlite3
  pool: 5
  database: eventreg_development
