development:
  adapter: mysql2
  encoding: utf8
  database: eventreg_development
  username: root
  password: letmein
  host: localhost
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  database: eventreg_test
  username: root
  password: letmein
  host: localhost
  port: 3306

production:
  adapter: mysql2
  encoding: utf8
  database: sc_eventreg
  username: sc_eventreg
  password: cnxQDe2OA4IBSMNpPUXU
  host: localhost
  port: 3306